### ISSUE TITLE
base install image instead of using same image as LiveISO ?

### ISSUE THREAD

**Issue by killajoe** [endeavouros-team/Calamares-3.2.11#1]
https://github.com/endeavouros-team/Calamares-3.2.11/blob/23c4596c646ba8f2808e6c90080c8adec0212433/src/modules/unpackfs/unpackfs.conf#L27

What about having an Archlinux base image to unpack and the using netinstall to implement DE installs?
This would need to get a more minimal packages list for the live ISO what can be done by removing xfce4-goodies and only take the packages used by the Livesession

**Comment by Portergos** [comment]
- in 1 iso? It'd still need to be squashfs, due unpackfs module. May be possible to have base and base devel in one .sfs and the rest of the system into another .sfs (manjaro does something like this using aufs). I think would require some changes to build.sh and also the hooks files to mount everything at boot
- making  2 isos?
- turning the current iso into a "more minimal" like using openbox?

**Comment by Portergos** [comment]
Hoppefully i guess we passed this point already.
