### ISSUE TITLE
branding error

### ISSUE THREAD

**Issue by killajoe** [endeavouros-team/Calamares-3.2.11#2]
11:57:19 [2]: WARNING: Invalid or missing *slideshowAPI* in branding file.

**Comment by Portergos** [comment]
It's possbile that this new calamares version has something different from the previous. We only copied the previous endeavouros folder. Better check if there are differences (last changed 20 days ago) https://github.com/calamares/calamares/tree/master/src/branding

**Comment by killajoe** [comment]
https://github.com/calamares/calamares/blob/ca58b67eb95d7f4488e4dc662a8d09c6724dab11/src/branding/default/branding.desc#L96

so we are using option one ...

**Comment by Portergos** [comment]
ok
